---
directory: /opt/beets/media
library: /opt/beets/db/beets.db
import:
    write: false
    copy: false
    move: false
    resume: false
    autotag: false
plugins: store fetchart
fetchart:
    auto: false
store:
    zipdir: /opt/beets/media/store
